== GATHERER

[.notes]
--
* nouvelle APi qui va être complémentaire des streams
* ils sont arrivé en preview avec java 22, mais avant de vous parler des Gatherer, on va refaire
le point sur les Streams!
--

=== LES STREAMS :

[source, java]
----
List<String> names = Arrays.asList("Alice", "Bob", "Charlie", "David", "Eve", "Frank");

        List<String> result = names.stream()
                                   .filter(name -> name.startsWith("A"))
                                   .map(String::toUpperCase)
                                   .collect(Collectors.toList());


        System.out.println(result); // [ALICE]
----

--
[.step]
* opération *intermediaire*
* opération *terminal*
--

[.notes]
--
* (filter, map...), on peut par exemple enchainer map filter sans jamais s'arrêter
* on ne peut plus rien faire après (anymatch, findFirst, collect, count...)
--

=== Gatherer

--
[.step]
* *Gatherer* -> C'est une API, qui permet de définir n'importe quelle *opération intermediaire*
--

[%notitle]
=== Gatherer

[source,java]
----
List<String> result = names.stream()
                            .gather(Gatherers.fold(...)).toList()
----

[.notes]
--
* l idée est de rajouté sur Stream : une seule methode : gather
* et cette methode gather elle prend un gatherer
* pour ceux qui ont déja vu l'api des collectors, ça marche pareil (avec la methode collect)
* donc dans la methode Gatherers on a pleins de gatherer qui sont déja prédifinis
* nottament le .fold, qui permet de faire une agrégation de plusieurs valeur en une donnée unique
* mais nous on va surtout voir comment on creer notre propre gatherer
--

=== Un etat

[.notes]
--
* Mes opérations intermédiaire peuvent avoir un état
* Limit ça a un état : je suis obligé de compter le nombre d élément que j'ai déjà vu
* distinct ca a un état : je suis obligé de savoir si les éléments sont déjà passé, pour pas les renvoyer deux fois
* a contrario, le filter ne conserve pas d'état
--

[%notitle]
=== Le gatherer avec etat
--
[.step]
* Gatherer.of() utilises *4 méthodes*
* *initializer*  permet de creer un état en fournissant un supplier
* *integrator* reçoit un état, un élément et un *downstream*
* *combiner* pour les calculs en parallèle
* *finisher* traite les états restants
--

[.notes]
--
* Gatherer.of() utilise *4 méthodes*
* *initializer*  permet de creer un état en fournissant un supplier (fonction qui permet de créer cet état) (supplier) -> une fonction sans arguments qui renvoie une valeur.
* *integrator* reçoit un état, un élément, et un downstream, donc il peut changer l' état , c'est là ou tout se passe
* *downstream*  il permet d'interoger nos étapes suivantes pour savoir si ils veulent oui non des éléments suivant
* *combiner* si je fais des threads en parallèle , il faut étre capable de combiner des états pour retourner un état ( si j'ai plusieurs états sur
differents threads, comment les faire correspondre à un seul état (le combiner ça peut etre la concatenation des listes))
* *finisher* traite des états restant, et peut nous permettre de faire des opérations pour envoyer ces etats restants
--

=== Le gatherer sans etat

[source,java,highlight="6|7|8|9||11|15|16"]
----
List<String> artistes = List.of("Les Casseurs Flotteurs",
                                "Les Cowboys Fringuants",
                                "Hans Zimmer",
                                "The offspring");

 static Gatherer<String, ?, String> filterEndWithS() {
        return Gatherer.of((_, element, downstream) -> {
            if (element.endsWith("s")) {
                return downstream.push(element);
            }
            return true;
        });

    }
var result = artistes.stream()
                .gather(filterEndWithS())
                .toList();
 //resultat [Les Casseurs Flotteurs, Les Cowboys Fringuants]
----

[.notes]
--
* Pour commencer on type notre Gatherer <String, ?, String> type d'entée > type de notre état > et Type de notre élement de sortie
* L'objet downstream a une methode push: pousse un élement pour le stage suivant
* om a aussi un methode qui s'appel greedy qui veut dire = pas d'interruption
* push qui renvoie un boolean : donc il interoge les opérations suivante de notre stream, pour nous dire si ils acceptent des élements
* pour conclure, on renvoie vrai, car on fait un filter, on veut continuer a parcourir l'integralité de notre liste
--

[%notitle]
=== Gatherer
[source,java,highlight="7|8|9|11|18"]
----
List<String> artistes = List.of("Les Casseurs Flotteurs",
                                "Les Cowboys Fringuants",
                                "Hans Zimmer",
                                "The offspring");

   static Gatherer<String, ?, String> takeWhileNameStartWithL() {
        return Gatherer.of((_, element, downstream) -> {
            if (element.startsWith("L")) {
                return downstream.push(element);
            }
            return false;
        });
    }

var result = artistes.stream()
                .gather(takeWhileNameStartWithL())
                .toList();
 //resultat [Les Casseurs Flotteurs, Les Cowboys Fringuants]
----



=== Le gatherer avec etat


[%notitle]
=== Le gatherer avec etat
[source,java,highlight="5|8|9|14|16"]
----
    static Gatherer<String, ?, String> limitFirstThreeElement() {

        return Gatherer.of(
                //initializer
                () -> new Counter(0),
                (state, element, downstream) -> {
                    //integrator
                    if (state.counter++ == 3) {
                        return false;
                    }
                    return downstream.push(element);
                },
                //combiner
                (c1, c2) -> new Counter(c1.counter + c2.counter),
                //finisher
                (_, _) -> {
                }
        );
    }
//resultat [Les Casseurs Flotteurs, Les Cowboys Fringuants, Hans Zimmer]
----

[.notes]
--
* dès qu'on a un état on doit écrire le combiner et le finisher
* notre combiner sera appelé uniquement quand le stream sera parallèle (là ce n'est pas le cas)
* C'était intéressant tout ça hein ?
* Mais personnellement je n'ai pas encore trouver de cas précis dans le quel on utilisera des gatherers
--


