
== JEP 456 – Unnamed Variables & Patterns


=== JEP 456 – Unnamed Variables & Patterns

Permet d’utiliser le caractère "_" comme pattern ou variable anonyme

[.notes]
--
* Introduit en preview avec le JDK 21, elle est finalisée dans le JDK 22.
* le but est de rendre le code plus propre et plus expressif
* en simplifiant la gestion des variables non utilisée
--

=== Avant la JEP 456

[source, java]
----
        List<String> names = List.of("Thomas", "nicolas", "alice", "gérard");
        int count = 0;
        for (String name : names) {
            count++;
        }
        System.out.println(" le compte est de : " + count);
----
[source, java]
----
        try {
            Connection connect = DriverManager.getConnection("localhost", "onepoint", "free");
        } catch (SQLException sql) {
            System.out.println("ce n'est pas free");
        }
----

=== Après la JEP 456

[source, java]
----

        List<String> names = List.of("Thomas", "nicolas", "alice", "gérard");
        int count = 0;
        for (String _ : names) {
            count++;
        }
        System.out.println(" le compte est de : " + count);
----
[source, java]
----
        try {
            Connection _ = DriverManager.getConnection("localhost", "onepoint", "free");
        } catch (SQLException sql) {
            System.out.println("ce n'est pas free");
        }
----

=== Conclusion

[.step]
* *Lisibilité améliorée*
* *Réduction des avertissements*
* *Meilleure gestion*
* *Réduction de la charge cognitive*

[.notes]
--
* *Lisibilité améliorée* en supprimant les variables inutiles.
* *Réduction des avertissements* de variables non utilisées lors de la compilation.
* *Meilleure gestion* du pattern matching, lorsque certains éléments du modèle ne sont pas pertinents.
* *Réduction de la charge cognitive* pour les développeurs en éliminant les variables sans intérêt.
--