
== JEP 459 String Templates (2eme preview)


[.notes]
--
* un string template est un littéral de String qui vous permet d’incorporer des expressions et des variables.
--

[.step]
* *Interpolation* de chaîne de carractère réduisant la complexité de la syntaxe comparée aux utilisations traditionnelles.
* *améliorer* la sécurité en validant les chaînes dynamiques destinées à des systèmes tiers, comme SQL, JSON ou HTML.
* STR est un *template processor*, défini par java, inclus dans la JDK

[.notes]
--
* Un template processor est un outil utilisé pour générer dynamiquement du contenu en remplissant des "blancs"
dans des modèles (templates) avec des données spécifiques.
--

[source, java]
----
String name = "Joan";
String info = STR."My name is \{name}";
System.out.println(info);  // "My name is Joan"
----

[.notes]
--
* Un template expression se compose d'un template processor (par exemple, STR), du texte de modèle et des expressions à évaluer.
--

=== Avantage
[.step]
* *Lisible*.
* *Sécurisant*,
* *Simplicité*,
* *Flexibilité*,


[source, java]
----
STR."SELECT * FROM users WHERE name = :name AND age > :age"
----

[.notes]
--
* Lisibilité améliorée : La syntaxe permet de mélanger facilement texte et expressions tout en maintenant la clarté du code.
* en offrant des mécanismes de validation automatique (comme l'échappement des caractères spéciaux pour SQL ou HTML).
* Simplification de la composition de chaînes : Cela permet d'inclure facilement des valeurs calculées à l'exécution dans des chaînes de caractères.
* Flexibilité : Les bibliothèques Java peuvent définir des syntaxes de formatage spécifiques pour ces modèles.
Interaction avec d'autres langages : Elle simplifie l'utilisation d'APIs qui attendent des chaînes écrites dans des langages non Java, comme SQL, XML ou JSON.
Création de valeurs non chaîne : La possibilité de créer directement des objets à partir de texte structuré et d'expressions sans passer par une chaîne intermédiaire.
--

=== Et pour les DATES ?
[.step]
* *Correction* des problèmes liés à la manipulation des fuseaux horaires
* Amélioration de la *robustesse* et la *consistance* de la gestion des dates/heures

[.notes]
--
* Cela aide à prévenir des erreurs logiques, des incohérences de fuseau horaire, nottamenet heure été hiver
et des problèmes de formatage des dates qui pourraient indirectement nuire à la sécurité de l'application.
--
