
== Unnamed Variables & Patterns

[.step]
* Permet d’utiliser le caractère "_" comme pattern ou variable anonyme



[.notes]
--
* Introduit en preview avec le JDK 21, elle est finalisée dans le JDK 22.
--

=== Avant la feature

[source, java]
----
        Map<String, Integer> scores = Map.of(
            "Alice", 85,
            "Bob", 75,
            "Charlie", 90,
            "David", 60
        );

        Map<String, Integer> filteredScores = scores.entrySet()
            .stream()
            .filter(entry -> entry.getValue() >= 80)
            .collect(Collectors.toMap(
                entry -> entry.getKey(),
                entry -> entry.getValue()
            ));

        // Affichage des résultats
        Nom : Alice, Score : 85
        Nom : Charlie, Score : 90
----

[.notes]
--
* le but est de rendre le code plus propre et plus expressif
* en simplifiant la gestion des variables non utilisée
--


=== Après la feature

[source, java]
----
          Map<String, Integer> scores = Map.of(
            "Alice", 85,
            "Bob", 75,
            "Charlie", 90,
            "David", 60
        );
        Map<String, Integer> filteredScores = scores.entrySet()
            .stream()
            .filter(_ -> _.getValue() <= 80)
            .collect(Collectors.toMap(
                _ -> _.getKey(),
                _ -> _.getValue()
            ));
        // Affichage des résultats
        Nom : David, Score : 60
        Nom : Bob, Score : 75
    }
----

=== Récap

[.step]
* *Lisibilité améliorée*
* *Réduction des avertissements*
* *Meilleure gestion*
* *Réduction de la charge cognitive*

[.notes]
--
* Java a enfin pris une fonctionnalité interessante de nos amis fronteux -> oui, ca existe depuis longtemps chez eux !
* *Lisibilité améliorée* en supprimant les variables inutiles.
* *Réduction des avertissements* de variables non utilisées lors de la compilation.
* *Meilleure gestion* du pattern matching, lorsque certains éléments du modèle ne sont pas pertinents.
* *Réduction de la charge cognitive* pour les développeurs en éliminant les variables sans intérêt.
--