
== JEP 456 – Unnamed Variables & Patterns

[%notitle]
=== Contenu des parties

permet d’utiliser _ comme pattern ou variable anonyme


[.notes]
--
 * Introduire dans le langage Java des variables et des motifs non nommés, représentés par le caractère souligné _.
Cela permet de déclarer des variables ou des motifs nécessaires mais jamais utilisés, clarifiant ainsi l’intention des développeurs et réduisant les erreurs potentielles.
--

[%notitle]
=== Avant apres

[source, java]
----
 List<String> names = List.of("Thomas", "nicolas", "alice", "gérard");
        int count = 0;
        for(String name: names){
            count++;
        }
        System.out.println(" le compte est de : " + count);
----

[source, java]
----

      List<String> names = List.of("Thomas", "nicolas", "alice", "gérard");
        int count = 0;
        for(String _: names){
            count++;
        }
        System.out.println(" le compte est de : " + count);
    }

----

[%notitle]
=== Avec pattern

[source, java]
----
   try {
            Connection connect = DriverManager.getConnection("localhost", "onepoint", "free");
        } catch (SQLException sql) {
            System.out.println("ce n'est pas free");
        }
----

[source, java]
----
      try {
            Connection _ = DriverManager.getConnection("localhost", "onepoint", "free");
        } catch (SQLException sql) {
            System.out.println("ce n'est pas free");
        }
----



[.step]
* Introduit en preview avec le JDK 21, cette fonctionnalité est *finalisée* sans modifications dans le *JDK 22*.
* *Lisibilité améliorée* en supprimant les variables inutiles.
* La variable ne rentre pas dans le scop.
* *Réduction des avertissements* de variables non utilisées lors de la compilations.
* *Meilleure gestion* du pattern matching, lorsque certains éléments du modèle ne sont pas pertinents.
* *Réduction de la charge cognitive* pour les développeurs en éliminant les variables sans intérêt.

[.notes]
--
* JEP 456 est une évolution pragmatique pour rendre le code Java plus propre et plus expressif, tout en simplifiant la gestion des variables inutiles dans des situations spécifiques.
--